site_name: Podcasting 2.0 Unofficial Documentation
theme:
  name: material 
  features:
    - navigation.tabs
    - navigation.indexes
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
nav:
  - 'Podcasting 2.0': 'index.md'
  - 'For Listeners': 'for-listeners/index.md'
  - 'For Podcasters': 'for-podcasters/index.md'
  - 'For Developers': 'for-developers/index.md'